[package]
name = "webpush-bridge"
description = "Interface between a Web Push service and platform push services (FCM, APNs)"
keywords = ["webpush", "push", "fcm", "apns"]
categories = ["network-programming"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde_json.workspace = true

[lints]
workspace = true
